// Mock data for courses
export const courses = [
  {
    id: "cs301",
    code: "CS301",
    name: "Data Structures & Algorithms",
    instructor: "Dr. Sarah Johnson",
    credits: 4,
    schedule: "Mon, Wed 10:00 AM - 11:30 AM",
    location: "Block B, Room 203",
    progress: 65,
    grade: "B+",
    status: "active",
    semester: "Fall 2023",
    gradePercentage: 85,
  },
  {
    id: "cs305",
    code: "CS305",
    name: "Database Systems",
    instructor: "Prof. Michael Chen",
    credits: 3,
    schedule: "Tue, Thu 2:00 PM - 3:30 PM",
    location: "Computer Lab 2",
    progress: 70,
    grade: "A-",
    status: "active",
    semester: "Fall 2023",
    gradePercentage: 90,
  },
  {
    id: "math201",
    code: "MATH201",
    name: "Discrete Mathematics",
    instructor: "Dr. Robert Williams",
    credits: 3,
    schedule: "Mon, Fri 9:00 AM - 10:30 AM",
    location: "Block A, Room 105",
    progress: 55,
    grade: "B",
    status: "active",
    semester: "Fall 2023",
    gradePercentage: 80,
  },
  {
    id: "eng203",
    code: "ENG203",
    name: "Technical Communication",
    instructor: "Prof. Emily Parker",
    credits: 2,
    schedule: "Wed 2:00 PM - 4:00 PM",
    location: "Block C, Room 110",
    progress: 80,
    grade: "A",
    status: "active",
    semester: "Fall 2023",
    gradePercentage: 95,
  },
  {
    id: "cs205",
    code: "CS205",
    name: "Computer Networks",
    instructor: "Dr. James Wilson",
    credits: 3,
    schedule: "Tue, Thu 11:00 AM - 12:30 PM",
    location: "Block B, Room 105",
    progress: 60,
    grade: "B",
    status: "active",
    semester: "Fall 2023",
    gradePercentage: 82,
  },
]

// Get course by ID
export function getCourseById(id: string) {
  return courses.find((course) => course.id === id)
}

