import type {
  Course,
  Semester,
  GradeDistribution,
  TranscriptRequest,
  GradeAppeal,
  GradePoint,
  GradingSystem,
  TranscriptData,
  AcademicRecord,
} from "./types"

export const gradingSystem: GradingSystem[] = [
  { grade: "A", minScore: 70, maxScore: 100, points: 4.0, description: "Excellent" },
  { grade: "B+", minScore: 65, maxScore: 69, points: 3.5, description: "Very Good" },
  { grade: "B", minScore: 60, maxScore: 64, points: 3.0, description: "Good" },
  { grade: "C+", minScore: 55, maxScore: 59, points: 2.5, description: "Fairly Good" },
  { grade: "C", minScore: 50, maxScore: 54, points: 2.0, description: "Average" },
  { grade: "D+", minScore: 45, maxScore: 49, points: 1.5, description: "Below Average" },
  { grade: "D", minScore: 40, maxScore: 44, points: 1.0, description: "Pass" },
  { grade: "E", minScore: 0, maxScore: 39, points: 0.0, description: "Fail" },
]

export const mockCourses: Course[] = [
  {
    id: "c1",
    code: "CSC 101",
    title: "Introduction to Computer Science",
    credits: 3,
    grade: "A",
    score: 85,
    status: "completed",
    semester: "Fall 2022",
    academicYear: "2022/2023",
  },
  {
    id: "c2",
    code: "MAT 101",
    title: "Calculus I",
    credits: 4,
    grade: "B+",
    score: 68,
    status: "completed",
    semester: "Fall 2022",
    academicYear: "2022/2023",
  },
  {
    id: "c3",
    code: "PHY 101",
    title: "Physics I",
    credits: 4,
    grade: "B",
    score: 63,
    status: "completed",
    semester: "Fall 2022",
    academicYear: "2022/2023",
  },
  {
    id: "c4",
    code: "ENG 101",
    title: "Communication Skills",
    credits: 3,
    grade: "A",
    score: 82,
    status: "completed",
    semester: "Fall 2022",
    academicYear: "2022/2023",
  },
  {
    id: "c5",
    code: "CSC 102",
    title: "Programming Fundamentals",
    credits: 3,
    grade: "A",
    score: 90,
    status: "completed",
    semester: "Spring 2023",
    academicYear: "2022/2023",
  },
  {
    id: "c6",
    code: "MAT 102",
    title: "Calculus II",
    credits: 4,
    grade: "B",
    score: 64,
    status: "completed",
    semester: "Spring 2023",
    academicYear: "2022/2023",
  },
  {
    id: "c7",
    code: "PHY 102",
    title: "Physics II",
    credits: 4,
    grade: "C+",
    score: 58,
    status: "completed",
    semester: "Spring 2023",
    academicYear: "2022/2023",
  },
  {
    id: "c8",
    code: "CSC 201",
    title: "Data Structures and Algorithms",
    credits: 4,
    grade: "B+",
    score: 67,
    status: "completed",
    semester: "Fall 2023",
    academicYear: "2023/2024",
  },
  {
    id: "c9",
    code: "CSC 202",
    title: "Database Systems",
    credits: 3,
    grade: "A",
    score: 88,
    status: "completed",
    semester: "Fall 2023",
    academicYear: "2023/2024",
  },
  {
    id: "c10",
    code: "CSC 203",
    title: "Computer Networks",
    credits: 3,
    grade: "B",
    score: 62,
    status: "completed",
    semester: "Fall 2023",
    academicYear: "2023/2024",
  },
  {
    id: "c11",
    code: "CSC 204",
    title: "Software Engineering",
    credits: 4,
    status: "in-progress",
    semester: "Spring 2024",
    academicYear: "2023/2024",
  },
  {
    id: "c12",
    code: "CSC 205",
    title: "Operating Systems",
    credits: 3,
    status: "in-progress",
    semester: "Spring 2024",
    academicYear: "2023/2024",
  },
  {
    id: "c13",
    code: "CSC 206",
    title: "Web Development",
    credits: 3,
    status: "in-progress",
    semester: "Spring 2024",
    academicYear: "2023/2024",
  },
  {
    id: "c14",
    code: "CSC 207",
    title: "Artificial Intelligence",
    credits: 3,
    status: "in-progress",
    semester: "Spring 2024",
    academicYear: "2023/2024",
  },
  {
    id: "c15",
    code: "MAT 201",
    title: "Discrete Mathematics",
    credits: 3,
    grade: "C",
    score: 52,
    status: "completed",
    semester: "Fall 2023",
    academicYear: "2023/2024",
    isRetake: false,
  },
  {
    id: "c16",
    code: "CSC 105",
    title: "Introduction to Programming",
    credits: 3,
    grade: "E",
    score: 35,
    status: "failed",
    semester: "Fall 2022",
    academicYear: "2022/2023",
  },
  {
    id: "c17",
    code: "CSC 105",
    title: "Introduction to Programming",
    credits: 3,
    grade: "C+",
    score: 56,
    status: "completed",
    semester: "Spring 2023",
    academicYear: "2022/2023",
    isRetake: true,
  },
]

export const mockSemesters: Semester[] = [
  {
    id: "s1",
    name: "Fall 2022",
    academicYear: "2022/2023",
    courses: mockCourses.filter((c) => c.semester === "Fall 2022"),
    gpa: 3.42,
    totalCredits: 17,
    status: "completed",
    startDate: "2022-09-01",
    endDate: "2022-12-15",
  },
  {
    id: "s2",
    name: "Spring 2023",
    academicYear: "2022/2023",
    courses: mockCourses.filter((c) => c.semester === "Spring 2023"),
    gpa: 3.27,
    totalCredits: 14,
    status: "completed",
    startDate: "2023-01-15",
    endDate: "2023-05-10",
  },
  {
    id: "s3",
    name: "Fall 2023",
    academicYear: "2023/2024",
    courses: mockCourses.filter((c) => c.semester === "Fall 2023"),
    gpa: 3.38,
    totalCredits: 13,
    status: "completed",
    startDate: "2023-09-01",
    endDate: "2023-12-15",
  },
  {
    id: "s4",
    name: "Spring 2024",
    academicYear: "2023/2024",
    courses: mockCourses.filter((c) => c.semester === "Spring 2024"),
    gpa: 0,
    totalCredits: 12,
    status: "in-progress",
    startDate: "2024-01-15",
    endDate: "2024-05-10",
  },
]

export const mockGradeDistribution: GradeDistribution[] = [
  { grade: "A", count: 4, percentage: 28.6 },
  { grade: "B+", count: 2, percentage: 14.3 },
  { grade: "B", count: 3, percentage: 21.4 },
  { grade: "C+", count: 2, percentage: 14.3 },
  { grade: "C", count: 1, percentage: 7.1 },
  { grade: "D+", count: 0, percentage: 0 },
  { grade: "D", count: 0, percentage: 0 },
  { grade: "E", count: 1, percentage: 7.1 },
]

export const mockTranscriptRequests: TranscriptRequest[] = [
  {
    id: "tr1",
    requestDate: "2023-11-15",
    status: "completed",
    type: "official",
    copies: 2,
    deliveryMethod: "pickup",
    paymentStatus: "paid",
    paymentAmount: 1000,
    paymentDate: "2023-11-15",
    paymentReference: "PAY123456",
    estimatedCompletionDate: "2023-11-20",
    completionDate: "2023-11-18",
  },
  {
    id: "tr2",
    requestDate: "2024-03-10",
    status: "processing",
    type: "official",
    copies: 1,
    deliveryMethod: "email",
    deliveryAddress: "student@university.ac.ke",
    paymentStatus: "paid",
    paymentAmount: 500,
    paymentDate: "2024-03-10",
    paymentReference: "PAY789012",
    estimatedCompletionDate: "2024-03-15",
  },
  {
    id: "tr3",
    requestDate: "2024-04-05",
    status: "pending",
    type: "unofficial",
    copies: 1,
    deliveryMethod: "email",
    deliveryAddress: "student@university.ac.ke",
    paymentStatus: "pending",
    paymentAmount: 300,
  },
]

export const mockGradeAppeals: GradeAppeal[] = [
  {
    id: "ga1",
    courseId: "c15",
    courseName: "Discrete Mathematics",
    courseCode: "MAT 201",
    currentGrade: "C",
    expectedGrade: "B",
    reason: "I believe there was an error in grading my final exam. My calculated score should be higher.",
    supportingDocuments: ["final_exam_copy.pdf", "calculation_sheet.pdf"],
    status: "under-review",
    submissionDate: "2024-01-10",
  },
  {
    id: "ga2",
    courseId: "c7",
    courseName: "Physics II",
    courseCode: "PHY 102",
    currentGrade: "C+",
    expectedGrade: "B",
    reason: "My continuous assessment marks were not fully included in the final grade calculation.",
    supportingDocuments: ["ca_marks_evidence.pdf"],
    status: "approved",
    submissionDate: "2023-05-20",
    decisionDate: "2023-06-05",
    decisionReason: "After review, we found that some CA marks were indeed missing from the calculation.",
    facultyFeedback: "Grade has been updated to reflect the correct calculation.",
  },
  {
    id: "ga3",
    courseId: "c10",
    courseName: "Computer Networks",
    courseCode: "CSC 203",
    currentGrade: "B",
    expectedGrade: "A",
    reason: "I believe my project submission was not graded correctly.",
    supportingDocuments: ["project_submission.pdf", "project_feedback.pdf"],
    status: "rejected",
    submissionDate: "2024-01-05",
    decisionDate: "2024-01-20",
    decisionReason: "After careful review, the grading was found to be accurate according to the rubric.",
    facultyFeedback: "The project missed key requirements as outlined in the assignment specification.",
  },
  {
    id: "ga4",
    courseId: "c3",
    courseName: "Physics I",
    courseCode: "PHY 101",
    currentGrade: "B",
    expectedGrade: "B+",
    reason: "I believe my final exam score was miscalculated.",
    supportingDocuments: ["exam_answer_sheet.pdf"],
    status: "draft",
    submissionDate: "2024-04-01",
  },
]

export const mockGradePoints: GradePoint[] = [
  { semester: "Fall 2022", gpa: 3.42, cgpa: 3.42 },
  { semester: "Spring 2023", gpa: 3.27, cgpa: 3.35 },
  { semester: "Fall 2023", gpa: 3.38, cgpa: 3.36 },
  { semester: "Spring 2024", gpa: 0, cgpa: 3.36 },
]

export const mockTranscriptData: TranscriptData = {
  studentInfo: {
    name: "John Doe",
    registrationNumber: "SCT/001/2022",
    program: "Bachelor of Science in Computer Science",
    faculty: "Faculty of Science and Technology",
    admissionDate: "2022-09-01",
  },
  semesters: mockSemesters,
  cgpa: 3.36,
  totalCredits: 44,
  academicStanding: {
    cgpa: 3.36,
    classification: "Second Class Upper Division",
    status: "good",
    honorsEligible: true,
  },
  certifications: ["Introduction to Cybersecurity - Cisco Networking Academy", "Python Programming - Coursera"],
  specialNotes: ["Dean's List - Fall 2022", "Academic Excellence Award - 2023"],
}

export const mockAcademicRecord: AcademicRecord = {
  studentName: "John Doe",
  admissionNumber: "SCT/001/2022",
  program: "Bachelor of Science in Computer Science",
  faculty: "School of Computing and Technology",
  department: "Computer Science",
  currentLevel: "Year 2",
  admissionDate: "2022-09-01",
  expectedGraduationDate: "2026-08-31",
  semesters: [
    {
      id: "s1",
      name: "Fall 2022",
      academicYear: "2022/2023",
      courses: [
        {
          id: "c1",
          code: "CSC 101",
          title: "Introduction to Computer Science",
          credits: 3,
          grade: "A",
          score: 85,
          status: "completed",
          semester: "Fall 2022",
          academicYear: "2022/2023"
        },
        {
          id: "c2",
          code: "MAT 101",
          title: "Calculus I",
          credits: 4,
          grade: "B+",
          score: 68,
          status: "completed",
          semester: "Fall 2022",
          academicYear: "2022/2023"
        }
      ],
      gpa: 3.75,
      totalCredits: 7,
      status: "completed",
      startDate: "2022-09-01",
      endDate: "2022-12-15"
    },
    {
      id: "s2",
      name: "Spring 2023",
      academicYear: "2022/2023",
      courses: [
        {
          id: "c3",
          code: "CSC 102",
          title: "Programming Fundamentals",
          credits: 3,
          status: "in-progress",
          semester: "Spring 2023",
          academicYear: "2022/2023"
        },
        {
          id: "c4",
          code: "MAT 102",
          title: "Calculus II",
          credits: 4,
          status: "in-progress",
          semester: "Spring 2023",
          academicYear: "2022/2023"
        }
      ],
      gpa: 0,
      totalCredits: 7,
      status: "in-progress",
      startDate: "2023-01-15",
      endDate: "2023-05-30"
    }
  ],
  cgpa: 3.75,
  totalCreditHours: 14,
  scholarships: ["Merit Scholarship 2022", "Dean's List Award"],
  specialAwards: ["Best First Year Student"]
}
